source $HOME/.yadr/zsh/theme.zsh

source $HOME/.zprezto/runcoms/zshrc

for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
